-- Clean database
DROP ALL OBJECTS; 


-- Creating tables

-- Items
CREATE TABLE ITEM(
	ITM_PK_EANCODE INT PRIMARY KEY, 
	ITM_DESCRIPTION VARCHAR(255) NOT NULL
);

-- Item Categories
CREATE TABLE ITEM_CATEGORY(
	ITMCAT_FK_ITEM_EANCODE INT NOT NULL,
	ITMCAT_FK_CATEGORY_ID BIGINT NOT NULL,
	FOREIGN KEY(ITMCAT_FK_ITEM_EANCODE) REFERENCES ITEM(ITM_PK_EANCODE)
);
	
-- Categories
CREATE TABLE CATEGORY(
	CAT_PK_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	CAT_NAME VARCHAR(255) NOT NULL
);
	
-- Prices
CREATE TABLE PRICE(
	PRC_PK_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	PRC_PRICE DOUBLE NOT NULL,
	PRC_FK_ITEM_EANCODE INT NOT NULL
);

-- Stores
CREATE TABLE STORE(
	STR_PK_NAME VARCHAR(255) PRIMARY KEY
);
	
-- Stores & Prices
CREATE TABLE STORE_PRICE(
	STRPRC_PK_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	STRPRC_FK_STORE_NAME VARCHAR(255) NOT NULL,
	STRPRC_FK_PRICE_ID INT NOT NULL,
	FOREIGN KEY(STRPRC_FK_STORE_NAME) REFERENCES STORE(STR_PK_NAME),
	FOREIGN KEY(STRPRC_FK_PRICE_ID) REFERENCES PRICE(PRC_PK_ID)
);